# CMake generated Testfile for 
# Source directory: /home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests
# Build directory: /home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit_parser_metadata "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_parser_metadata" "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/../test_files/KTLX20260209_162244_V06")
set_tests_properties(unit_parser_metadata PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;7;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(unit_multi_product "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_multi_product" "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/../test_files/KTLX20260209_162244_V06")
set_tests_properties(unit_multi_product PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;12;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(unit_all_moments "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_all_moments" "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/../test_files/KABR20250621_041210_V06")
set_tests_properties(unit_all_moments PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;17;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(unit_threadpool "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_threadpool")
set_tests_properties(unit_threadpool PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;22;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(unit_aws_initializer "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_aws_initializer")
set_tests_properties(unit_aws_initializer PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;27;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(unit_decompression "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_decompression")
set_tests_properties(unit_decompression PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;32;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(unit_quantization "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_quantization")
set_tests_properties(unit_quantization PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;37;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(unit_gate_indexing "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_gate_indexing")
set_tests_properties(unit_gate_indexing PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;42;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(unit_frame_storage "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_frame_storage")
set_tests_properties(unit_frame_storage PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;47;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(unit_config_manager "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_config_manager")
set_tests_properties(unit_config_manager PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;52;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(integration_real_data "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_real_data")
set_tests_properties(integration_real_data PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;58;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(integration_volumetric_generation "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_volumetric_generation")
set_tests_properties(integration_volumetric_generation PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;63;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(integration_check_sequence "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/check_sequence" "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/../test_files/KTLX20260209_162244_V06")
set_tests_properties(integration_check_sequence PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;68;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(integration_benchmark_memory_concurrency "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/benchmark_memory_concurrency" "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/../test_files/KTLX20260209_162244_V06")
set_tests_properties(integration_benchmark_memory_concurrency PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;73;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(integration_deadlock_simulation "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/deadlock_simulation")
set_tests_properties(integration_deadlock_simulation PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;78;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(integration_repro_munmap "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/repro_munmap")
set_tests_properties(integration_repro_munmap PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;83;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
add_test(fuzz_corrupt_data "/home/joshua/.zenflow/worktrees/parser-fixes-9402/build_asan/test/code_tests/test_fuzz_corrupt_data" "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/../test_files/KTLX20260209_162244_V06")
set_tests_properties(fuzz_corrupt_data PROPERTIES  _BACKTRACE_TRIPLES "/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;89;add_test;/home/joshua/.zenflow/worktrees/parser-fixes-9402/test/code_tests/CMakeLists.txt;0;")
